### ISSUE TITLE
Setting for changing the slug

### ISSUE THREAD

**Issue by primozcigler** [devinsays/portfolio-post-type#73]
Hi Devin,

We use this plugin with one of our themes and added the setting in customizer to change the slug of the plugin.
Obviously it would be better to have such a setting somewhere in the admin dashboard, so the relevant settings can be kept together. Not even a new page is needed I think, this could be added to Settings > Permalinks, so all permalinks settings are kept in one place.

How do you feel about this idea? If I provide the code and create a PR for a simple setting page where one can translate/change default slug, would you merge it?

**Comment by devinsays** [comment]
Hi @primozcigler. I'd like to avoid extra complexity with this plugin (which come with adding a settings page pr customizer tab, saving/sanitizing a slug value, etc). We've provided filters to change all the post type args- so you're welcome to add the customizer option with your theme and use the filters to change the slug.

Thanks for the feedback though!
