### ISSUE TITLE
Save the post_format

### ISSUE THREAD

**Issue by CreaboxThemes** [devinsays/portfolio-post-type#74]
Hi Devin,

I'm customizing the plugin to save the post format. I have added 'post-formats' in the array $supports, but I don't get to save the post format in the database as the posts.

I would be grateful if you can help me.

Thanks and regards

**Comment by devinsays** [comment]
You would filter the $args that enable support when the post type is registered:

```
function custom_portfolio_formats( $args ) {
	$args['supports'] = array_merge( array( 'post-formats' ), $args['supports'] );
	return $args;
}
add_filter( 'portfolioposttype_args', 'custom_portfolio_formats' );
```
