### ISSUE TITLE
Error notice (trying to get property of non-object) in Woocommerce setup wizard

### ISSUE THREAD

**Issue by jordif** [devinsays/portfolio-post-type#76]
First, thanks for sharing the plugin!

One small issue: i'm using the Portfolio Post Type plugin and I've also installed WooCoomerce. After activating Woocommerce, you're directed to the Woocommerce Setup Wizard and the following error shows up (i have wp_debug enabled):

"Notice: Trying to get property of non-object in /wp-content/plugins/portfolio-post-type/includes/class-portfolio-post-type-admin.php on line 197"

I think this could be fixed by changing that line to:

```
if ( !is_object($screen) || $screen->id != 'dashboard' ) {
```

Not sure if you're still maintaining the plugin. Thanks anyway,

Jordi

**Comment by devinsays** [comment]
Thanks for the bug report! Updated.
