### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by joeyavino** [devinsays/portfolio-post-type#79]
This isn't really an issue but not sure if someone can help me.  I'm new to WP.  I'm using this plugin with the Kabuto theme and I'd like to:

1:  Increase the width of the columns.  Right now, at full width I can fix 6 items across, I'd like to only fit 4.

2:  Anyone know a good tutorial or can help me add custom attributes to the portfolio?  I'm using this as a modeling site so I'd like to add fields here for Height, Waist, Hips, etc: http://screencast.com/t/p5g4Yjd2ecE

**Comment by devinsays** [comment]
This plugin just sets up the post type for the dashboard. Styling on the front end is outside the scope of this plugin. You can contact the theme author perhaps?
