### ISSUE TITLE
PHP Notices

### ISSUE THREAD

**Issue by KTS915** [devinsays/portfolio-post-type#83]
Testing this on PHP7, and I am getting the following notices when on the dashboard:

```
Array to string conversion
wp-content/plugins/portfolio-post-type/includes/class-gamajo-dashboard-glancer.php:122

Undefined property: stdClass::$Array
wp-content/plugins/portfolio-post-type/includes/class-gamajo-dashboard-glancer.php:122
```

**Comment by GaryJones** [comment]
@devinsays This was [fixed](https://github.com/GaryJones/Gamajo-Dashboard-Glancer/commit/f4aee0bb33f410e7f96468db6304a23820e14a1a) in Gamajo Dashboard Glancer 1.0.2 back in August 2015. Just needs the include file updated.

**Comment by devinsays** [comment]
Thanks for the bug report @KTS915 and fix @GaryJones. Just committed. Will roll out a release shortly.
