### ISSUE TITLE
Change link archive portfolio to custome page link

### ISSUE THREAD

**Issue by nitogel** [devinsays/portfolio-post-type#85]
Hi!
Can you help me? I need change breadcrumbs link to portfolio archive with custom page url.
How I can do this?
Replacing archive-portfolio.php is long way for me.
Thank you.

**Comment by GaryJones** [comment]
It will depends on how your breadcrumbs are being built - plugin or theme.

**Comment by nitogel** [comment]
I use "Breadcrumb NavXT" plugin.

**Comment by nitogel** [comment]
I've got! In plugin settengs.
