### ISSUE TITLE
Q: Why does my archive-portfolio only show 10 items?

### ISSUE THREAD

**Issue by grobmeier** [devinsays/portfolio-post-type#87]
Hello,
thanks for the plugin. I have a question regarding the portfolio overview.

We did something like: 

```
		<?php if ( have_posts() ) : ?>
			<?php while ( have_posts() ) : the_post(); ?>
				<?php
					get_template_part( 'content', 'portfolio' );
				?>
			<?php endwhile; ?>
```

It only returns 10 portfolio items max, even when we have setup more. Do you have a better approach for this?

Thanks!

**Comment by devinsays** [comment]
It defaults to your reading settings under "Settings > Reading".

You could override this by doing a custom query with an alternate posts_per_page setting, or override globally using a pre_get_posts filter.
