### ISSUE TITLE
First post title is displaying when on a category page

### ISSUE THREAD

**Issue by sully1107** [devinsays/portfolio-post-type#89]
Hi, 

The plugin came with a theme that I brought called Heavico. When using the plugin everything works fine, but when you go onto a category page where it displays all projects, the title that is pulled through is first project in that category instead of the category title.

Do you know if there's any way to work around this?

Regards,

Matt

**Comment by devinsays** [comment]
You'll need to contact the theme author about this. Or you can check out titles are displayed in the PHO code, which is generally in the archive.php template.
