### ISSUE TITLE
Problem with the uninstallation of the plugin

### ISSUE THREAD

**Issue by Eniotnas** [devinsays/portfolio-post-type#96]
Hello, I've tested your plugin, but once I tried to uninstall it, it didn't do that properly, and even without having him in my plugins menu, the features of the plugin are still here. 

Right know I am using another portfolio plugin but unfortunately he cannot work properly because of portfolio-post-type.
I would like to know how can I uninstall portfolio-post-type properly.

Sorry for the terrible English I am French...

**Comment by devinsays** [comment]
This plugin doesn't save any settings into the database. If you disable it, the menu option should disappear. However, your portfolio content does not get deleted. If you want to delete that, you should delete those portfolio posts before disabling the plugin.
